spring.application.name=First

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=MYDB4PM
spring.datasource.password=MYDB4PM
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

server.port=4041